### ISSUE TITLE
Is the python-docx module required for successfully running the script?

### ISSUE THREAD

**Issue by Marcio2536** [to-be-to-see/coursehero-make-file#2]
I am currently using python 3.12.5 on Windows. When I installed all required module specified in the source code, the script still prompts error. 

Error Message: 
```
(chvenv) C:\Users\<username>\apps\coursehero-make-file-main>python main.py
Traceback (most recent call last):
  File "C:\Users\<username>\apps\coursehero-make-file-main\main.py", line 2, in <module>
    from docx import Document
  File "C:\Users\<username>\apps\coursehero-make-file-main\chvenv\Lib\site-packages\docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'
```
This is solved by installing the python-docx module. Therefore, is it only me that was encountering the same problem, or this should be included as a general requirement?

Link for reference: [here](https://stackoverflow.com/questions/22765313/when-import-docx-in-python3-3-i-have-error-importerror-no-module-named-excepti)

**Comment by to-be-to-see** [comment]
Python-docx library is needed. The imported name is kind of misleading
😂.For the requirement.txt, I am not motivated to maintain the project so I
won't make any changes.

在 2024年9月3日週二 下午8:00，Edmond ***@***.***> 寫道：
